/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.*;
import Negocios.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Brian Anco
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() throws ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
        rsutilities.RSUtilities.setOpaqueVentana(this,false);
        
        lblMensaje.setText("");
    }
    FrmPrincipal Principal = new FrmPrincipal();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new RSMaterialComponent.RSPanelShadow();
        jPanel2 = new javax.swing.JPanel();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        rSPanelImage1 = new rojeru_san.rspanel.RSPanelImage();
        txtUsuario = new rojeru_san.RSMTextFull();
        txtPassword = new rojeru_san.RSMPassView();
        btnIngresar = new rojerusan.RSButtonHover();
        rSPanelImage2 = new rojerusan.RSPanelImage();
        lblMensaje = new javax.swing.JLabel();
        rSButtonMaterialIconUno1 = new RSMaterialComponent.RSButtonMaterialIconUno();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(255, 255, 255));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(255, 255, 255));
        rSPanelGradiente1.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.VERTICAL);
        rSPanelGradiente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/LogoOmylab.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        rSPanelGradiente1.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 200, 55));

        txtUsuario.setForeground(new java.awt.Color(51, 51, 51));
        txtUsuario.setBordeColorFocus(new java.awt.Color(244, 146, 34));
        txtUsuario.setBotonColor(new java.awt.Color(244, 146, 34));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.setPlaceholder("Nro. Documento");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 180, -1));

        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setBordeColorFocus(new java.awt.Color(244, 146, 34));
        txtPassword.setBotonColor(new java.awt.Color(244, 146, 34));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setPlaceholder("Contraseña");
        rSPanelGradiente1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 180, -1));

        btnIngresar.setBackground(new java.awt.Color(237, 125, 52));
        btnIngresar.setText("→");
        btnIngresar.setColorHover(new java.awt.Color(251, 169, 76));
        btnIngresar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIngresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 50, 50));

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/Base.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage2Layout = new javax.swing.GroupLayout(rSPanelImage2);
        rSPanelImage2.setLayout(rSPanelImage2Layout);
        rSPanelImage2Layout.setHorizontalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        rSPanelImage2Layout.setVerticalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        rSPanelGradiente1.add(rSPanelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, -1));

        lblMensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(150, 0, 0));
        lblMensaje.setText("¡Usuario/Contraseña incorrectos!");
        rSPanelGradiente1.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        rSButtonMaterialIconUno1.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMaterialIconUno1.setForeground(new java.awt.Color(153, 0, 0));
        rSButtonMaterialIconUno1.setBackgroundHover(new java.awt.Color(204, 204, 204));
        rSButtonMaterialIconUno1.setForegroundHover(new java.awt.Color(153, 0, 0));
        rSButtonMaterialIconUno1.setForegroundIcon(new java.awt.Color(153, 0, 0));
        rSButtonMaterialIconUno1.setForegroundIconHover(new java.awt.Color(153, 0, 0));
        rSButtonMaterialIconUno1.setForegroundText(new java.awt.Color(153, 0, 0));
        rSButtonMaterialIconUno1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSButtonMaterialIconUno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconUno1ActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(rSButtonMaterialIconUno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 40, -1));

        jPanel2.add(rSPanelGradiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 470));

        rSPanelShadow1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        Boolean Llave=false;
        if(txtUsuario.getText().isEmpty()||txtPassword.getText().isEmpty()){
            lblMensaje.setText("         ¡Campos requeridos!");
        }
        else{
            ClsNEmpleado objNC=new ClsNEmpleado();
            ClsNHistorial objNH=new ClsNHistorial();
            ClsEHistorial objEH = new ClsEHistorial();
            for(ClsEEmpleado objE:objNC.MtdListarEmpleado()){
                if(txtUsuario.getText().equals(String.valueOf(objE.getNro_documento())) &&
                        txtPassword.getText().equals(objE.getClave())){
                    Llave=true;
                    Principal.lblNombres.setText(objE.getNombre());
                    Principal.lblDni.setText(objE.getNro_documento());
                    Principal.lblApellidos.setText(objE.getApellido());
                    Principal.lblRol.setText(objE.getIdRol()+"");
                    Date date = new Date();
                    DateFormat FechaHora = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                    objEH.setFecha(FechaHora.format(date)+"");
                    objEH.setTipo("Iniciar Sesion");
                    objEH.setAccion(objE.getNombre()+" "+objE.getApellido()+ " inicio sesion.");
                    objEH.setNro_doc(objE.getNro_documento());
                    if(objNH.MtdRegistrarHistorial(objEH)==true){
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Error al registrar acción.");
                    }
                    
                    
                }
            }

            if(Llave==true){
                this.dispose();
                Principal.setVisible(true);
                
            }
            else{
                lblMensaje.setText("¡Usuario/Contraseña incorrectos!");
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void rSButtonMaterialIconUno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconUno1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSButtonMaterialIconUno1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmLogin().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnIngresar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMensaje;
    private RSMaterialComponent.RSButtonMaterialIconUno rSButtonMaterialIconUno1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage1;
    private rojerusan.RSPanelImage rSPanelImage2;
    private RSMaterialComponent.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSMPassView txtPassword;
    private rojeru_san.RSMTextFull txtUsuario;
    // End of variables declaration//GEN-END:variables
}
