/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.ClsEHistorial;
import Entidad.*;
import Entidad.ClsERol_Permiso;
import Negocios.*;
import rojerusan.RSPanelsSlider;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Brian Anco
 */
public class FrmPrincipal extends javax.swing.JFrame implements ActionListener {

    PnlInicio pnlInicio = new PnlInicio();
    PnlOrdenes pnlOrdenes = new PnlOrdenes();
    PnlEmpleado pnlEmpleados = new PnlEmpleado();
    PnlCliente pnlClientes = new PnlCliente();
    PnlProveedor pnlProveedores = new PnlProveedor();
    PnlAnalisis pnlAnalisis = new PnlAnalisis();
    PnlAlmacen pnlAlmacen = new PnlAlmacen();
    PnlResultados pnlResultados = new PnlResultados();
    PnlHistorial pnlHistorial = new PnlHistorial();
    PnlMantenimiento pnlMantenimiento = new PnlMantenimiento();
    PnlVentas pnlVentas = new PnlVentas();
    PnlRoles pnlRoles = new PnlRoles();
    PnlReportes pnlReportes = new PnlReportes();
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() throws ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
        
        pnlSlider.add(pnlInicio);
        pnlInicio.setVisible(true);
        pnlOrdenes.setVisible(false);
        pnlEmpleados.setVisible(false);
        pnlClientes.setVisible(false);
        pnlProveedores.setVisible(false);
        pnlAnalisis.setVisible(false);
        pnlAlmacen.setVisible(false);
        pnlResultados.setVisible(false);
        pnlHistorial.setVisible(false);
        pnlMantenimiento.setVisible(false);
        pnlVentas.setVisible(false);
        pnlRoles.setVisible(false);
        pnlReportes.setVisible(false);
        
        btnCompras.addActionListener(this);
        btnInicio.addActionListener(this);
        btnOrdenes.addActionListener(this);
        btnResultados.addActionListener(this);
        btnAnalisis.addActionListener(this);
        btnAlmacen.addActionListener(this);
        btnClientes.addActionListener(this);
        btnEmpleados.addActionListener(this);
        btnProveedores.addActionListener(this);
        btnReportes.addActionListener(this);
        btnHistorial.addActionListener(this);
        btnMantenimiento.addActionListener(this);
        btnRoles.addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modi
     * fy this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuIzquierda = new rspanelgradiente.RSPanelGradiente();
        btnAlmacen = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnInicio = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnResultados = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnAnalisis = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnClientes = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnEmpleados = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnProveedores = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnCerrarSesion = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnOrdenes = new RSMaterialComponent.RSButtonMaterialIconOne();
        pnlMenuSuperior = new rspanelgradiente.RSPanelGradiente();
        rSPanelImage4 = new rojeru_san.rspanel.RSPanelImage();
        rSPanelImage1 = new rojeru_san.rspanel.RSPanelImage();
        rSPanelImage3 = new rojeru_san.rspanel.RSPanelImage();
        rSPanelImage5 = new rojeru_san.rspanel.RSPanelImage();
        rSPanelImage6 = new rojeru_san.rspanel.RSPanelImage();
        btnOrdenes3 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSPanelImage2 = new rojeru_san.rspanel.RSPanelImage();
        btnRoles = new RSMaterialComponent.RSButtonMaterialOne();
        btnMantenimiento = new RSMaterialComponent.RSButtonMaterialOne();
        btnHistorial = new RSMaterialComponent.RSButtonMaterialOne();
        btnReportes = new RSMaterialComponent.RSButtonMaterialOne();
        btnCompras = new RSMaterialComponent.RSButtonMaterialOne();
        lblDni = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        pnlSlider = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenuIzquierda.setColorPrimario(new java.awt.Color(244, 146, 34));
        pnlMenuIzquierda.setColorSecundario(new java.awt.Color(244, 146, 34));
        pnlMenuIzquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAlmacen.setBackground(new java.awt.Color(244, 146, 34));
        btnAlmacen.setText("  Almacén");
        btnAlmacen.setBackgroundHover(new java.awt.Color(251, 169, 76));
        btnAlmacen.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAlmacen.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.VIEW_LIST);
        pnlMenuIzquierda.add(btnAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 45));
        btnAlmacen.getAccessibleContext().setAccessibleName("Inicio");

        btnInicio.setBackground(new java.awt.Color(251, 169, 76));
        btnInicio.setText("  Inicio");
        btnInicio.setBackgroundHover(new java.awt.Color(251, 169, 76));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnInicio.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        pnlMenuIzquierda.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 45));

        btnResultados.setBackground(new java.awt.Color(244, 146, 34));
        btnResultados.setText("  Resultados");
        btnResultados.setBackgroundHover(new java.awt.Color(251, 169, 76));
        btnResultados.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnResultados.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK_CIRCLE);
        pnlMenuIzquierda.add(btnResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 45));

        btnAnalisis.setBackground(new java.awt.Color(244, 146, 34));
        btnAnalisis.setText("  Análisis");
        btnAnalisis.setBackgroundHover(new java.awt.Color(251, 169, 76));
        btnAnalisis.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAnalisis.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BOOK);
        pnlMenuIzquierda.add(btnAnalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 200, 45));

        btnClientes.setBackground(new java.awt.Color(244, 146, 34));
        btnClientes.setText("  Clientes");
        btnClientes.setBackgroundHover(new java.awt.Color(251, 169, 76));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnClientes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        pnlMenuIzquierda.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, 200, 45));

        btnEmpleados.setBackground(new java.awt.Color(244, 146, 34));
        btnEmpleados.setText("  Empleados");
        btnEmpleados.setBackgroundHover(new java.awt.Color(251, 169, 76));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnEmpleados.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.WORK);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        pnlMenuIzquierda.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 45));

        btnProveedores.setBackground(new java.awt.Color(244, 146, 34));
        btnProveedores.setText("  Proveedores");
        btnProveedores.setBackgroundHover(new java.awt.Color(251, 169, 76));
        btnProveedores.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnProveedores.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CONTACTS);
        pnlMenuIzquierda.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 345, 200, 45));

        btnCerrarSesion.setBackground(new java.awt.Color(244, 146, 34));
        btnCerrarSesion.setText("  Cerrar Sesión");
        btnCerrarSesion.setBackgroundHover(new java.awt.Color(251, 169, 76));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCerrarSesion.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXIT_TO_APP);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlMenuIzquierda.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 200, 45));

        btnOrdenes.setBackground(new java.awt.Color(244, 146, 34));
        btnOrdenes.setText("  Órdenes");
        btnOrdenes.setBackgroundHover(new java.awt.Color(251, 169, 76));
        btnOrdenes.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnOrdenes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ASSIGNMENT);
        btnOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenesActionPerformed(evt);
            }
        });
        pnlMenuIzquierda.add(btnOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 200, 45));

        getContentPane().add(pnlMenuIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 570));

        pnlMenuSuperior.setColorPrimario(new java.awt.Color(255, 255, 255));
        pnlMenuSuperior.setColorSecundario(new java.awt.Color(255, 255, 255));
        pnlMenuSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage4.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/ventas.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage4Layout = new javax.swing.GroupLayout(rSPanelImage4);
        rSPanelImage4.setLayout(rSPanelImage4Layout);
        rSPanelImage4Layout.setHorizontalGroup(
            rSPanelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        rSPanelImage4Layout.setVerticalGroup(
            rSPanelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        pnlMenuSuperior.add(rSPanelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 5, -1, -1));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/LogoOmylab.png"))); // NOI18N
        rSPanelImage1.setPreferredSize(new java.awt.Dimension(44, 44));

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMenuSuperior.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 50));

        rSPanelImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/clientes.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage3Layout = new javax.swing.GroupLayout(rSPanelImage3);
        rSPanelImage3.setLayout(rSPanelImage3Layout);
        rSPanelImage3Layout.setHorizontalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        rSPanelImage3Layout.setVerticalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        pnlMenuSuperior.add(rSPanelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 5, -1, -1));

        rSPanelImage5.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/mantenimiento.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage5Layout = new javax.swing.GroupLayout(rSPanelImage5);
        rSPanelImage5.setLayout(rSPanelImage5Layout);
        rSPanelImage5Layout.setHorizontalGroup(
            rSPanelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        rSPanelImage5Layout.setVerticalGroup(
            rSPanelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        pnlMenuSuperior.add(rSPanelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 5, -1, -1));

        rSPanelImage6.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/reportes.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage6Layout = new javax.swing.GroupLayout(rSPanelImage6);
        rSPanelImage6.setLayout(rSPanelImage6Layout);
        rSPanelImage6Layout.setHorizontalGroup(
            rSPanelImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        rSPanelImage6Layout.setVerticalGroup(
            rSPanelImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        pnlMenuSuperior.add(rSPanelImage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 5, -1, -1));

        btnOrdenes3.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdenes3.setForeground(new java.awt.Color(102, 102, 102));
        btnOrdenes3.setBackgroundHover(new java.awt.Color(204, 204, 204));
        btnOrdenes3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnOrdenes3.setForegroundHover(new java.awt.Color(102, 102, 102));
        btnOrdenes3.setForegroundIcon(new java.awt.Color(102, 102, 102));
        btnOrdenes3.setForegroundIconHover(new java.awt.Color(102, 102, 102));
        btnOrdenes3.setForegroundText(new java.awt.Color(102, 102, 102));
        btnOrdenes3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        btnOrdenes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenes3ActionPerformed(evt);
            }
        });
        pnlMenuSuperior.add(btnOrdenes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 1, 70, 68));

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/historial.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage2Layout = new javax.swing.GroupLayout(rSPanelImage2);
        rSPanelImage2.setLayout(rSPanelImage2Layout);
        rSPanelImage2Layout.setHorizontalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        rSPanelImage2Layout.setVerticalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        pnlMenuSuperior.add(rSPanelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 5, 35, 35));

        btnRoles.setBackground(new java.awt.Color(255, 255, 255));
        btnRoles.setForeground(new java.awt.Color(102, 102, 102));
        btnRoles.setText("Roles/Permisos");
        btnRoles.setBackgroundHover(new java.awt.Color(204, 204, 204));
        btnRoles.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnRoles.setForegroundHover(new java.awt.Color(102, 102, 102));
        btnRoles.setForegroundText(new java.awt.Color(102, 102, 102));
        btnRoles.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnRoles.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRoles.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolesActionPerformed(evt);
            }
        });
        pnlMenuSuperior.add(btnRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 1, 160, 100));

        btnMantenimiento.setBackground(new java.awt.Color(255, 255, 255));
        btnMantenimiento.setForeground(new java.awt.Color(102, 102, 102));
        btnMantenimiento.setText("Mantenimiento");
        btnMantenimiento.setBackgroundHover(new java.awt.Color(204, 204, 204));
        btnMantenimiento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMantenimiento.setForegroundHover(new java.awt.Color(102, 102, 102));
        btnMantenimiento.setForegroundText(new java.awt.Color(102, 102, 102));
        btnMantenimiento.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnMantenimiento.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMantenimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });
        pnlMenuSuperior.add(btnMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1, 160, 100));

        btnHistorial.setBackground(new java.awt.Color(255, 255, 255));
        btnHistorial.setForeground(new java.awt.Color(102, 102, 102));
        btnHistorial.setText("Historial");
        btnHistorial.setBackgroundHover(new java.awt.Color(204, 204, 204));
        btnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnHistorial.setForegroundHover(new java.awt.Color(102, 102, 102));
        btnHistorial.setForegroundText(new java.awt.Color(102, 102, 102));
        btnHistorial.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnHistorial.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHistorial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        pnlMenuSuperior.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 1, 160, 100));

        btnReportes.setBackground(new java.awt.Color(255, 255, 255));
        btnReportes.setForeground(new java.awt.Color(102, 102, 102));
        btnReportes.setText("Reportes");
        btnReportes.setBackgroundHover(new java.awt.Color(204, 204, 204));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnReportes.setForegroundHover(new java.awt.Color(102, 102, 102));
        btnReportes.setForegroundText(new java.awt.Color(102, 102, 102));
        btnReportes.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnReportes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        pnlMenuSuperior.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 160, 100));

        btnCompras.setBackground(new java.awt.Color(255, 255, 255));
        btnCompras.setForeground(new java.awt.Color(102, 102, 102));
        btnCompras.setText("Compras/Ventas");
        btnCompras.setBackgroundHover(new java.awt.Color(204, 204, 204));
        btnCompras.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCompras.setForegroundHover(new java.awt.Color(102, 102, 102));
        btnCompras.setForegroundText(new java.awt.Color(102, 102, 102));
        btnCompras.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnCompras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        pnlMenuSuperior.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1, 160, 100));

        lblDni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDni.setForeground(new java.awt.Color(102, 102, 102));
        lblDni.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDni.setText("DNI");
        lblDni.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlMenuSuperior.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 48, 120, -1));

        lblNombres.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(102, 102, 102));
        lblNombres.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombres.setText("Nombre1 Nombre2");
        lblNombres.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlMenuSuperior.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 8, 120, -1));

        lblApellidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(102, 102, 102));
        lblApellidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellidos.setText("DNI");
        lblApellidos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlMenuSuperior.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 28, 120, -1));

        lblRol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRol.setForeground(new java.awt.Color(255, 255, 255));
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRol.setText("DNI");
        lblRol.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlMenuSuperior.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 20, 20));

        getContentPane().add(pnlMenuSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        pnlSlider.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 1010, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        ClsNHistorial objNH=new ClsNHistorial();
        ClsEHistorial objEH = new ClsEHistorial();
        Date date = new Date();
        DateFormat FechaHora = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        objEH.setFecha(FechaHora.format(date)+"");
        objEH.setTipo("Cerrar Sesion");
        objEH.setAccion(lblNombres.getText()+" "+lblApellidos.getText()+ " cerro sesion.");
        objEH.setNro_doc(lblDni.getText());
        if(objNH.MtdRegistrarHistorial(objEH)==true){
        }
        else{
            JOptionPane.showMessageDialog(null, "Error al registrar accion.");
        }
        this.dispose();
        try {
            new FrmLogin().setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnOrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenesActionPerformed

    }//GEN-LAST:event_btnOrdenesActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed

    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnOrdenes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrdenes3ActionPerformed

    private void btnRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRolesActionPerformed

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmPrincipal().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void actionPerformed(ActionEvent e){
        Object evt=e.getSource();
        ClsNRol_Permiso objNRP = new ClsNRol_Permiso();
        int llave=0;
        if (evt.equals(btnInicio))
        {
            llave=1;
            if(llave==1){
                pnlInicio.setVisible(true);
                pnlOrdenes.setVisible(false);
                pnlEmpleados.setVisible(false);
                pnlClientes.setVisible(false);
                pnlProveedores.setVisible(false);
                pnlAlmacen.setVisible(false);
                pnlAnalisis.setVisible(false);
                pnlResultados.setVisible(false);
                pnlHistorial.setVisible(false);
                pnlMantenimiento.setVisible(false);
                pnlVentas.setVisible(false);
                pnlRoles.setVisible(false);
                pnlReportes.setVisible(false);
                pnlSlider.add(pnlInicio);
                pnlSlider.validate();

                //Cambiar el color del botón:
                btnInicio.setBackground(new java.awt.Color(251,169,76));
                btnOrdenes.setBackground(new java.awt.Color(244,146,34));
                btnResultados.setBackground(new java.awt.Color(244,146,34));
                btnAnalisis.setBackground(new java.awt.Color(244,146,34));
                btnAlmacen.setBackground(new java.awt.Color(244,146,34));
                btnClientes.setBackground(new java.awt.Color(244,146,34));
                btnEmpleados.setBackground(new java.awt.Color(244,146,34));
                btnProveedores.setBackground(new java.awt.Color(244,146,34));
                btnMantenimiento.setBackground(new java.awt.Color(255,255,255));
                btnHistorial.setBackground(new java.awt.Color(255,255,255));
                btnCompras.setBackground(new java.awt.Color(255,255,255));
                btnRoles.setBackground(new java.awt.Color(255,255,255));
                btnReportes.setBackground(new java.awt.Color(255,255,255));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
            
        }
        if (evt.equals(btnOrdenes))
        {
            for(ClsERol_Permiso objE:objNRP.MtdListarRol_Permiso()){
                if(objE.getIdRol()==Integer.parseInt(lblRol.getText())&&objE.getIdPermiso()==1){
                    llave=1;
                }
            }
            if(llave==1){
                 pnlInicio.setVisible(false);
                pnlOrdenes.setVisible(true);
                pnlEmpleados.setVisible(false);
                pnlClientes.setVisible(false);
                pnlProveedores.setVisible(false);
                pnlAlmacen.setVisible(false);
                pnlAnalisis.setVisible(false);
                pnlResultados.setVisible(false);
                pnlHistorial.setVisible(false);
                pnlMantenimiento.setVisible(false);
                pnlVentas.setVisible(false);
                pnlRoles.setVisible(false);
                pnlReportes.setVisible(false);
                pnlSlider.add(pnlOrdenes);
                pnlSlider.validate();

                //Cambiar el color del botón:
                btnInicio.setBackground(new java.awt.Color(244,146,34));
                btnOrdenes.setBackground(new java.awt.Color(251,169,76));
                btnResultados.setBackground(new java.awt.Color(244,146,34));
                btnAnalisis.setBackground(new java.awt.Color(244,146,34));
                btnAlmacen.setBackground(new java.awt.Color(244,146,34));
                btnClientes.setBackground(new java.awt.Color(244,146,34));
                btnEmpleados.setBackground(new java.awt.Color(244,146,34));
                btnProveedores.setBackground(new java.awt.Color(244,146,34));
                btnMantenimiento.setBackground(new java.awt.Color(255,255,255));
                btnHistorial.setBackground(new java.awt.Color(255,255,255));
                btnCompras.setBackground(new java.awt.Color(255,255,255));
                btnRoles.setBackground(new java.awt.Color(255,255,255));
                btnReportes.setBackground(new java.awt.Color(255,255,255));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
           
        }
        if (evt.equals(btnEmpleados))
        {
            for(ClsERol_Permiso objE:objNRP.MtdListarRol_Permiso()){
                if(objE.getIdRol()==Integer.parseInt(lblRol.getText())&&objE.getIdPermiso()==5){
                    llave=1;
                }
            }
            if(llave==1){
                pnlInicio.setVisible(false);
                pnlOrdenes.setVisible(false);
                pnlEmpleados.setVisible(true);
                pnlClientes.setVisible(false);
                pnlProveedores.setVisible(false);
                pnlAlmacen.setVisible(false);
                pnlAnalisis.setVisible(false);
                pnlResultados.setVisible(false);
                pnlHistorial.setVisible(false);
                pnlMantenimiento.setVisible(false);
                pnlVentas.setVisible(false);
                pnlRoles.setVisible(false);
                pnlReportes.setVisible(false);
                pnlSlider.add(pnlEmpleados);
                pnlSlider.validate();

                //Cambiar el color del botón:
                btnInicio.setBackground(new java.awt.Color(244,146,34));
                btnOrdenes.setBackground(new java.awt.Color(244,146,34));
                btnResultados.setBackground(new java.awt.Color(244,146,34));
                btnAnalisis.setBackground(new java.awt.Color(244,146,34));
                btnAlmacen.setBackground(new java.awt.Color(244,146,34));
                btnClientes.setBackground(new java.awt.Color(244,146,34));
                btnEmpleados.setBackground(new java.awt.Color(251,169,76));
                btnProveedores.setBackground(new java.awt.Color(244,146,34));
                btnMantenimiento.setBackground(new java.awt.Color(255,255,255));
                btnHistorial.setBackground(new java.awt.Color(255,255,255));
                btnCompras.setBackground(new java.awt.Color(255,255,255));
                btnRoles.setBackground(new java.awt.Color(255,255,255));
                btnReportes.setBackground(new java.awt.Color(255,255,255));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
            
        }
        if (evt.equals(btnClientes))
        {
            for(ClsERol_Permiso objE:objNRP.MtdListarRol_Permiso()){
                if(objE.getIdRol()==Integer.parseInt(lblRol.getText())&&objE.getIdPermiso()==4){
                    llave=1;
                }
            }
            if(llave==1){
                pnlInicio.setVisible(false);
                pnlOrdenes.setVisible(false);
                pnlEmpleados.setVisible(false);
                pnlProveedores.setVisible(false);
                pnlClientes.setVisible(true);
                pnlAlmacen.setVisible(false);
                pnlAnalisis.setVisible(false);
                pnlResultados.setVisible(false);
                pnlHistorial.setVisible(false);
                pnlMantenimiento.setVisible(false);
                pnlVentas.setVisible(false);
                pnlRoles.setVisible(false);
                pnlReportes.setVisible(false);
                pnlSlider.add(pnlClientes);
                pnlSlider.validate();

                //Cambiar el color del botón:
                btnInicio.setBackground(new java.awt.Color(244,146,34));
                btnOrdenes.setBackground(new java.awt.Color(244,146,34));
                btnResultados.setBackground(new java.awt.Color(244,146,34));
                btnAnalisis.setBackground(new java.awt.Color(244,146,34));
                btnAlmacen.setBackground(new java.awt.Color(244,146,34));
                btnClientes.setBackground(new java.awt.Color(251,169,76));
                btnEmpleados.setBackground(new java.awt.Color(244,146,34));
                btnProveedores.setBackground(new java.awt.Color(244,146,34));
                btnMantenimiento.setBackground(new java.awt.Color(255,255,255));
                btnHistorial.setBackground(new java.awt.Color(255,255,255));
                btnCompras.setBackground(new java.awt.Color(255,255,255));
                btnRoles.setBackground(new java.awt.Color(255,255,255));
                btnReportes.setBackground(new java.awt.Color(255,255,255));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
            
        }
        
        if (evt.equals(btnProveedores))
        {
            for(ClsERol_Permiso objE:objNRP.MtdListarRol_Permiso()){
                if(objE.getIdRol()==Integer.parseInt(lblRol.getText())&&objE.getIdPermiso()==6){
                    llave=1;
                }
            }
            if(llave==1){
                pnlInicio.setVisible(false);
            pnlOrdenes.setVisible(false);
            pnlEmpleados.setVisible(false);
            pnlProveedores.setVisible(true);
            pnlClientes.setVisible(false);
            pnlAlmacen.setVisible(false);
            pnlAnalisis.setVisible(false);
            pnlResultados.setVisible(false);
            pnlHistorial.setVisible(false);
            pnlMantenimiento.setVisible(false);
            pnlVentas.setVisible(false);
            pnlRoles.setVisible(false);
            pnlReportes.setVisible(false);
            pnlSlider.add(pnlProveedores);
            pnlSlider.validate();
            
            //Cambiar el color del botón:
            btnInicio.setBackground(new java.awt.Color(244,146,34));
            btnOrdenes.setBackground(new java.awt.Color(244,146,34));
            btnResultados.setBackground(new java.awt.Color(244,146,34));
            btnAnalisis.setBackground(new java.awt.Color(244,146,34));
            btnAlmacen.setBackground(new java.awt.Color(244,146,34));
            btnClientes.setBackground(new java.awt.Color(244,146,34));
            btnEmpleados.setBackground(new java.awt.Color(244,146,34));
            btnProveedores.setBackground(new java.awt.Color(251,169,76));
            btnMantenimiento.setBackground(new java.awt.Color(255,255,255));
            btnHistorial.setBackground(new java.awt.Color(255,255,255));
            btnCompras.setBackground(new java.awt.Color(255,255,255));
            btnRoles.setBackground(new java.awt.Color(255,255,255));
            btnReportes.setBackground(new java.awt.Color(255,255,255));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
            
        }
        
        if (evt.equals(btnAlmacen))
        {
            for(ClsERol_Permiso objE:objNRP.MtdListarRol_Permiso()){
                if(objE.getIdRol()==Integer.parseInt(lblRol.getText())&&objE.getIdPermiso()==12){
                    llave=1;
                }
            }
            if(llave==1){
                pnlInicio.setVisible(false);
            pnlOrdenes.setVisible(false);
            pnlEmpleados.setVisible(false);
            pnlProveedores.setVisible(false);
            pnlClientes.setVisible(false);
            pnlAlmacen.setVisible(true);
            pnlAnalisis.setVisible(false);
            pnlResultados.setVisible(false);
            pnlHistorial.setVisible(false);
            pnlMantenimiento.setVisible(false);
            pnlVentas.setVisible(false);
            pnlRoles.setVisible(false);
            pnlReportes.setVisible(false);
            pnlSlider.add(pnlAlmacen);
            pnlSlider.validate();
            
            //Cambiar el color del botón:
            btnInicio.setBackground(new java.awt.Color(244,146,34));
            btnOrdenes.setBackground(new java.awt.Color(244,146,34));
            btnResultados.setBackground(new java.awt.Color(244,146,34));
            btnAnalisis.setBackground(new java.awt.Color(244,146,34));
            btnAlmacen.setBackground(new java.awt.Color(251,169,76));
            btnClientes.setBackground(new java.awt.Color(244,146,34));
            btnEmpleados.setBackground(new java.awt.Color(244,146,34));
            btnProveedores.setBackground(new java.awt.Color(244,146,34));
            btnMantenimiento.setBackground(new java.awt.Color(255,255,255));
            btnHistorial.setBackground(new java.awt.Color(255,255,255));
            btnCompras.setBackground(new java.awt.Color(255,255,255));
            btnRoles.setBackground(new java.awt.Color(255,255,255));
            btnReportes.setBackground(new java.awt.Color(255,255,255));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
            
        }
        
        if (evt.equals(btnAnalisis))
        {
            for(ClsERol_Permiso objE:objNRP.MtdListarRol_Permiso()){
                if(objE.getIdRol()==Integer.parseInt(lblRol.getText())&&objE.getIdPermiso()==3){
                    llave=1;
                }
            }
            if(llave==1){
                pnlInicio.setVisible(false);
                pnlOrdenes.setVisible(false);
                pnlEmpleados.setVisible(false);
                pnlProveedores.setVisible(false);
                pnlClientes.setVisible(false);
                pnlAlmacen.setVisible(false);
                pnlAnalisis.setVisible(true);
                pnlResultados.setVisible(false);
                pnlHistorial.setVisible(false);
                pnlMantenimiento.setVisible(false);
                pnlVentas.setVisible(false);
                pnlRoles.setVisible(false);
                pnlReportes.setVisible(false);
                pnlSlider.add(pnlAnalisis);
                pnlSlider.validate();

                //Cambiar el color del botón:
                btnInicio.setBackground(new java.awt.Color(244,146,34));
                btnOrdenes.setBackground(new java.awt.Color(244,146,34));
                btnResultados.setBackground(new java.awt.Color(244,146,34));
                btnAnalisis.setBackground(new java.awt.Color(251,169,76));
                btnAlmacen.setBackground(new java.awt.Color(244,146,34));
                btnClientes.setBackground(new java.awt.Color(244,146,34));
                btnEmpleados.setBackground(new java.awt.Color(244,146,34));
                btnProveedores.setBackground(new java.awt.Color(244,146,34));
                btnMantenimiento.setBackground(new java.awt.Color(255,255,255));
                btnHistorial.setBackground(new java.awt.Color(255,255,255));
                btnCompras.setBackground(new java.awt.Color(255,255,255));
                btnRoles.setBackground(new java.awt.Color(255,255,255));
                btnReportes.setBackground(new java.awt.Color(255,255,255));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
            
        }
        
        if (evt.equals(btnResultados))
        {
            for(ClsERol_Permiso objE:objNRP.MtdListarRol_Permiso()){
                if(objE.getIdRol()==Integer.parseInt(lblRol.getText())&&objE.getIdPermiso()==2){
                    llave=1;
                }
            }
            if(llave==1){
                pnlInicio.setVisible(false);
                pnlOrdenes.setVisible(false);
                pnlEmpleados.setVisible(false);
                pnlProveedores.setVisible(false);
                pnlClientes.setVisible(false);
                pnlAlmacen.setVisible(false);
                pnlAnalisis.setVisible(false);
                pnlResultados.setVisible(true);
                pnlHistorial.setVisible(false);
                pnlMantenimiento.setVisible(false);
                pnlVentas.setVisible(false);
                pnlRoles.setVisible(false);
                pnlReportes.setVisible(false);
                pnlSlider.add(pnlResultados);
                pnlSlider.validate();
                //Cambiar el color del botón:
                btnInicio.setBackground(new java.awt.Color(244,146,34));
                btnOrdenes.setBackground(new java.awt.Color(244,146,34));
                btnResultados.setBackground(new java.awt.Color(251,169,76));
                btnAnalisis.setBackground(new java.awt.Color(244,146,34));
                btnAlmacen.setBackground(new java.awt.Color(244,146,34));
                btnClientes.setBackground(new java.awt.Color(244,146,34));
                btnEmpleados.setBackground(new java.awt.Color(244,146,34));
                btnProveedores.setBackground(new java.awt.Color(244,146,34));
                btnMantenimiento.setBackground(new java.awt.Color(255,255,255));
                btnHistorial.setBackground(new java.awt.Color(255,255,255));
                btnCompras.setBackground(new java.awt.Color(255,255,255));
                btnRoles.setBackground(new java.awt.Color(255,255,255));
                btnReportes.setBackground(new java.awt.Color(255,255,255));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
            
        }
        
        if (evt.equals(btnHistorial))
        {
            for(ClsERol_Permiso objE:objNRP.MtdListarRol_Permiso()){
                if(objE.getIdRol()==Integer.parseInt(lblRol.getText())&&objE.getIdPermiso()==11){
                    llave=1;
                }
            }
            if(llave==1){
                pnlInicio.setVisible(false);
                pnlOrdenes.setVisible(false);
                pnlEmpleados.setVisible(false);
                pnlProveedores.setVisible(false);
                pnlClientes.setVisible(false);
                pnlAlmacen.setVisible(false);
                pnlAnalisis.setVisible(false);
                pnlResultados.setVisible(false);
                pnlHistorial.setVisible(true);
                pnlMantenimiento.setVisible(false);
                pnlVentas.setVisible(false);
                pnlRoles.setVisible(false);
                pnlReportes.setVisible(false);
                pnlSlider.add(pnlHistorial);
                pnlSlider.validate();

                //Cambiar el color del botón:
                btnInicio.setBackground(new java.awt.Color(244,146,34));
                btnOrdenes.setBackground(new java.awt.Color(244,146,34));
                btnResultados.setBackground(new java.awt.Color(244,146,34));
                btnAnalisis.setBackground(new java.awt.Color(244,146,34));
                btnAlmacen.setBackground(new java.awt.Color(244,146,34));
                btnClientes.setBackground(new java.awt.Color(244,146,34));
                btnEmpleados.setBackground(new java.awt.Color(244,146,34));
                btnProveedores.setBackground(new java.awt.Color(244,146,34));
                btnMantenimiento.setBackground(new java.awt.Color(255,255,255));
                btnHistorial.setBackground(new java.awt.Color(204,204,204));
                btnCompras.setBackground(new java.awt.Color(255,255,255));
                btnRoles.setBackground(new java.awt.Color(255,255,255));
                btnReportes.setBackground(new java.awt.Color(255,255,255));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
            
        }
        
        if (evt.equals(btnMantenimiento))
        {
            for(ClsERol_Permiso objE:objNRP.MtdListarRol_Permiso()){
                if(objE.getIdRol()==Integer.parseInt(lblRol.getText())&&objE.getIdPermiso()==7){
                    llave=1;
                }
            }
            if(llave==1){
                pnlInicio.setVisible(false);
                pnlOrdenes.setVisible(false);
                pnlEmpleados.setVisible(false);
                pnlProveedores.setVisible(false);
                pnlClientes.setVisible(false);
                pnlAlmacen.setVisible(false);
                pnlAnalisis.setVisible(false);
                pnlResultados.setVisible(false);
                pnlHistorial.setVisible(false);
                pnlMantenimiento.setVisible(true);
                pnlVentas.setVisible(false);
                pnlRoles.setVisible(false);
                pnlReportes.setVisible(false);
                pnlSlider.add(pnlMantenimiento);
                pnlSlider.validate();

                //Cambiar el color del botón:
                btnInicio.setBackground(new java.awt.Color(244,146,34));
                btnOrdenes.setBackground(new java.awt.Color(244,146,34));
                btnResultados.setBackground(new java.awt.Color(244,146,34));
                btnAnalisis.setBackground(new java.awt.Color(244,146,34));
                btnAlmacen.setBackground(new java.awt.Color(244,146,34));
                btnClientes.setBackground(new java.awt.Color(244,146,34));
                btnEmpleados.setBackground(new java.awt.Color(244,146,34));
                btnProveedores.setBackground(new java.awt.Color(244,146,34));
                btnMantenimiento.setBackground(new java.awt.Color(204,204,204));
                btnHistorial.setBackground(new java.awt.Color(255,255,255));
                btnCompras.setBackground(new java.awt.Color(255,255,255));
                btnRoles.setBackground(new java.awt.Color(255,255,255));
                btnReportes.setBackground(new java.awt.Color(255,255,255));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
            
        }
        
        if (evt.equals(btnCompras))
        {
            for(ClsERol_Permiso objE:objNRP.MtdListarRol_Permiso()){
                if(objE.getIdRol()==Integer.parseInt(lblRol.getText())&&objE.getIdPermiso()==8){
                    llave=1;
                }
            }
            if(llave==1){
                pnlInicio.setVisible(false);
                pnlOrdenes.setVisible(false);
                pnlEmpleados.setVisible(false);
                pnlProveedores.setVisible(false);
                pnlClientes.setVisible(false);
                pnlAlmacen.setVisible(false);
                pnlAnalisis.setVisible(false);
                pnlResultados.setVisible(false);
                pnlHistorial.setVisible(false);
                pnlMantenimiento.setVisible(false);
                pnlVentas.setVisible(true);
                pnlRoles.setVisible(false);
                pnlReportes.setVisible(false);
                pnlSlider.add(pnlVentas);
                pnlSlider.validate();

                //Cambiar el color del botón:
                btnInicio.setBackground(new java.awt.Color(244,146,34));
                btnOrdenes.setBackground(new java.awt.Color(244,146,34));
                btnResultados.setBackground(new java.awt.Color(244,146,34));
                btnAnalisis.setBackground(new java.awt.Color(244,146,34));
                btnAlmacen.setBackground(new java.awt.Color(244,146,34));
                btnClientes.setBackground(new java.awt.Color(244,146,34));
                btnEmpleados.setBackground(new java.awt.Color(244,146,34));
                btnProveedores.setBackground(new java.awt.Color(244,146,34));
                btnMantenimiento.setBackground(new java.awt.Color(255,255,255));
                btnHistorial.setBackground(new java.awt.Color(255,255,255));
                btnCompras.setBackground(new java.awt.Color(204,204,204));
                btnRoles.setBackground(new java.awt.Color(255,255,255));
                btnReportes.setBackground(new java.awt.Color(255,255,255));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
            
        }
        
        if (evt.equals(btnRoles))
        {
            for(ClsERol_Permiso objE:objNRP.MtdListarRol_Permiso()){
                if(objE.getIdRol()==Integer.parseInt(lblRol.getText())&&objE.getIdPermiso()==10){
                    llave=1;
                }
            }
            if(llave==1){
                pnlInicio.setVisible(false);
                pnlOrdenes.setVisible(false);
                pnlEmpleados.setVisible(false);
                pnlProveedores.setVisible(false);
                pnlClientes.setVisible(false);
                pnlAlmacen.setVisible(false);
                pnlAnalisis.setVisible(false);
                pnlResultados.setVisible(false);
                pnlHistorial.setVisible(false);
                pnlMantenimiento.setVisible(false);
                pnlVentas.setVisible(false);
                pnlRoles.setVisible(true);
                pnlReportes.setVisible(false);
                pnlSlider.add(pnlRoles);
                pnlSlider.validate();

                //Cambiar el color del botón:
                btnInicio.setBackground(new java.awt.Color(244,146,34));
                btnOrdenes.setBackground(new java.awt.Color(244,146,34));
                btnResultados.setBackground(new java.awt.Color(244,146,34));
                btnAnalisis.setBackground(new java.awt.Color(244,146,34));
                btnAlmacen.setBackground(new java.awt.Color(244,146,34));
                btnClientes.setBackground(new java.awt.Color(244,146,34));
                btnEmpleados.setBackground(new java.awt.Color(244,146,34));
                btnProveedores.setBackground(new java.awt.Color(244,146,34));
                btnMantenimiento.setBackground(new java.awt.Color(255,255,255));
                btnHistorial.setBackground(new java.awt.Color(255,255,255));
                btnCompras.setBackground(new java.awt.Color(255,255,255));
                btnRoles.setBackground(new java.awt.Color(204,204,204));
                btnReportes.setBackground(new java.awt.Color(255,255,255));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
            
        }
        if (evt.equals(btnReportes))
        {
            for(ClsERol_Permiso objE:objNRP.MtdListarRol_Permiso()){
                if(objE.getIdRol()==Integer.parseInt(lblRol.getText())&&objE.getIdPermiso()==9){
                    llave=1;
                }
            }
            if(llave==1){
                pnlInicio.setVisible(false);
                pnlOrdenes.setVisible(false);
                pnlEmpleados.setVisible(false);
                pnlProveedores.setVisible(false);
                pnlClientes.setVisible(false);
                pnlAlmacen.setVisible(false);
                pnlAnalisis.setVisible(false);
                pnlResultados.setVisible(false);
                pnlHistorial.setVisible(false);
                pnlMantenimiento.setVisible(false);
                pnlVentas.setVisible(false);
                pnlRoles.setVisible(false);
                pnlReportes.setVisible(true);
                pnlSlider.add(pnlReportes);
                pnlSlider.validate();

                //Cambiar el color del botón:
                btnInicio.setBackground(new java.awt.Color(244,146,34));
                btnOrdenes.setBackground(new java.awt.Color(244,146,34));
                btnResultados.setBackground(new java.awt.Color(244,146,34));
                btnAnalisis.setBackground(new java.awt.Color(244,146,34));
                btnAlmacen.setBackground(new java.awt.Color(244,146,34));
                btnClientes.setBackground(new java.awt.Color(244,146,34));
                btnEmpleados.setBackground(new java.awt.Color(244,146,34));
                btnProveedores.setBackground(new java.awt.Color(244,146,34));
                btnMantenimiento.setBackground(new java.awt.Color(255,255,255));
                btnHistorial.setBackground(new java.awt.Color(255,255,255));
                btnCompras.setBackground(new java.awt.Color(255,255,255));
                btnRoles.setBackground(new java.awt.Color(255,255,255));
                btnReportes.setBackground(new java.awt.Color(204,204,204));
            }
            else{
                JOptionPane.showMessageDialog(null,"El usuario no tiene permiso para ver el formulario.");
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btnAlmacen;
    private RSMaterialComponent.RSButtonMaterialIconOne btnAnalisis;
    private RSMaterialComponent.RSButtonMaterialIconOne btnCerrarSesion;
    private RSMaterialComponent.RSButtonMaterialIconOne btnClientes;
    private RSMaterialComponent.RSButtonMaterialOne btnCompras;
    private RSMaterialComponent.RSButtonMaterialIconOne btnEmpleados;
    private RSMaterialComponent.RSButtonMaterialOne btnHistorial;
    private RSMaterialComponent.RSButtonMaterialIconOne btnInicio;
    private RSMaterialComponent.RSButtonMaterialOne btnMantenimiento;
    private RSMaterialComponent.RSButtonMaterialIconOne btnOrdenes;
    private RSMaterialComponent.RSButtonMaterialIconOne btnOrdenes3;
    private RSMaterialComponent.RSButtonMaterialIconOne btnProveedores;
    private RSMaterialComponent.RSButtonMaterialOne btnReportes;
    private RSMaterialComponent.RSButtonMaterialIconOne btnResultados;
    private RSMaterialComponent.RSButtonMaterialOne btnRoles;
    public static javax.swing.JLabel lblApellidos;
    public static javax.swing.JLabel lblDni;
    public static javax.swing.JLabel lblNombres;
    public static javax.swing.JLabel lblRol;
    private rspanelgradiente.RSPanelGradiente pnlMenuIzquierda;
    private rspanelgradiente.RSPanelGradiente pnlMenuSuperior;
    private javax.swing.JPanel pnlSlider;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage1;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage2;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage3;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage4;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage5;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage6;
    // End of variables declaration//GEN-END:variables
}
