/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocios.*;
import Entidad.*;
import Entidad.ClsETipo_documento;
import javax.swing.table.DefaultTableModel;
import Negocios.ClsNCliente;
import Negocios.*;
import Negocios.ClsNTipo_documento;
import static Presentacion.FrmPrincipal.lblApellidos;
import static Presentacion.FrmPrincipal.lblDni;
import static Presentacion.FrmPrincipal.lblNombres;
import static Presentacion.PnlMantenimiento.ListarTipoMedida;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Brian Anco
 */
public class PnlCliente extends javax.swing.JPanel {

    /**
     * Creates new form PnlOrdenes
     */
    
    public PnlCliente() {
        initComponents();
        ListarCliente();
        LimpiarCliente();
        LlenarComboRoTipoDoc();
    }
    public static void LlenarComboRoTipoDoc() {
        cboTipoDoc.removeAllItems();        
        ClsNTipo_documento objNR=new ClsNTipo_documento();
            for(ClsETipo_documento  objR:objNR.MtdListarTipo_documento()){
                String tipo_doc=String.valueOf(objR.getDescripcion());
                if(tipo_doc.equals("BOLETA")||tipo_doc.equals("FACTURA")){
                    int a;
                }
                else{
                    cboTipoDoc.addItem(String.valueOf(objR.getDescripcion()));
                }
            }    
    }
    public void LimpiarCliente(){
        txtNumDoc.setEditable(true);
        txtNombres.setEditable(true);
        txtApellidos.setEditable(true);
        txtNumDoc.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtDireccion.setText("");
        txtCorreo.setText("");
        txtCelular.setText("");
        txtClave.setText("");
    }
    public static void ListarCliente(){
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        try {
            int filas=tblClientes.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
        ClsNCliente objNC=new ClsNCliente();
        String[] datos=new String[9];
        for(ClsECliente objE:objNC.MtdListarCliente()){
            datos[0]=objE.getNro_documento();
            datos[1]=objE.getNombre();
            datos[2]=objE.getApellido();
            datos[3]=String.valueOf(objE.getFech_nacimiento()) ;
            datos[4]=objE.getSexo();
            datos[5]=objE.getDireccion();
            datos[6]=objE.getCorreo();
            datos[7]=objE.getCelular();
            datos[8]=String.valueOf(objE.getIdTip_documento());
            
            modelo.addRow(datos);
        }
        TableRowSorter<TableModel> Id = new TableRowSorter<TableModel>(modelo);
        tblClientes.setRowSorter(Id);
        tblClientes.getRowSorter().toggleSortOrder(2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanel1 = new necesario.RSPanel();
        jLabel1 = new javax.swing.JLabel();
        rSPanel2 = new necesario.RSPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        cboSexo = new javax.swing.JComboBox<>();
        txtApellidos = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        btnBuscarDNI = new RSMaterialComponent.RSButtonMaterialIconOne();
        txtDireccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lblFecha2 = new javax.swing.JLabel();
        lblFecha1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnEditar = new RSMaterialComponent.RSButtonMaterialIconOne();
        lblNombre2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        lblNombre1 = new javax.swing.JLabel();
        txtCalendar = new com.toedter.calendar.JDateChooser();
        txtNumDoc = new javax.swing.JTextField();
        btnLimpiar = new RSMaterialComponent.RSButtonMaterialIconOne();
        cboTipoDoc = new javax.swing.JComboBox<>();
        txtClave = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanel1.setColorBackground(new java.awt.Color(255, 255, 255));
        rSPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 73, 51));
        jLabel1.setText("GESTIONAR CLIENTES");
        rSPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        rSPanel2.setColorBackground(new java.awt.Color(255, 255, 255));
        rSPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(235, 73, 51));
        jLabel6.setText("GESTIONAR CLIENTES");
        rSPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Nro. Doc.");
        rSPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, -1, -1));

        txtNombres.setEditable(false);
        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombres.setPreferredSize(new java.awt.Dimension(150, 28));
        rSPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 330, -1));

        lblSexo.setBackground(new java.awt.Color(0, 0, 0));
        lblSexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSexo.setText("Sexo");
        rSPanel2.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 305, -1, -1));

        cboSexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cboSexo.setName(""); // NOI18N
        cboSexo.setPreferredSize(new java.awt.Dimension(93, 28));
        rSPanel2.add(cboSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 130, -1));

        txtApellidos.setEditable(false);
        txtApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidos.setPreferredSize(new java.awt.Dimension(150, 28));
        rSPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 330, -1));

        lblApellido.setBackground(new java.awt.Color(0, 0, 0));
        lblApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblApellido.setText("Apellidos");
        rSPanel2.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 185, -1, -1));

        btnBuscarDNI.setBackground(new java.awt.Color(244, 146, 34));
        btnBuscarDNI.setBackgroundHover(new java.awt.Color(251, 169, 76));
        btnBuscarDNI.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDNIActionPerformed(evt);
            }
        });
        rSPanel2.add(btnBuscarDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 30, 28));

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDireccion.setPreferredSize(new java.awt.Dimension(150, 28));
        rSPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 330, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Dirección");
        rSPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, -1, -1));

        txtCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCelular.setPreferredSize(new java.awt.Dimension(150, 28));
        rSPanel2.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 120, -1));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Celular");
        rSPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 305, -1, -1));

        lblFecha2.setBackground(new java.awt.Color(0, 0, 0));
        lblFecha2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha2.setText("nacimiento");
        rSPanel2.add(lblFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 20));

        lblFecha1.setBackground(new java.awt.Color(0, 0, 0));
        lblFecha1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha1.setText("Fecha de");
        rSPanel2.add(lblFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreo.setPreferredSize(new java.awt.Dimension(150, 28));
        rSPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 330, -1));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Correo ");
        rSPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 265, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tipo Doc.");
        rSPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 105, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(56, 171, 38));
        btnGuardar.setBackgroundHover(new java.awt.Color(56, 178, 72));
        btnGuardar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        rSPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 30, 28));

        btnEditar.setBackground(new java.awt.Color(254, 221, 14));
        btnEditar.setBackgroundHover(new java.awt.Color(254, 218, 75));
        btnEditar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        rSPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 30, 28));

        lblNombre2.setBackground(new java.awt.Color(0, 0, 0));
        lblNombre2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre2.setText(" ");
        rSPanel2.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 60, -1));

        tblClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro. Doc.", "Nombres", "Apellidos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClientes);
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setResizable(false);
            tblClientes.getColumnModel().getColumn(0).setPreferredWidth(114);
            tblClientes.getColumnModel().getColumn(1).setResizable(false);
            tblClientes.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblClientes.getColumnModel().getColumn(2).setResizable(false);
            tblClientes.getColumnModel().getColumn(2).setPreferredWidth(210);
        }

        rSPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 530, 390));

        lblNombre1.setBackground(new java.awt.Color(0, 0, 0));
        lblNombre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre1.setText("Nombres");
        rSPanel2.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 145, -1, -1));

        txtCalendar.setDateFormatString("dd/MM/yyyy");
        rSPanel2.add(txtCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 330, 30));

        txtNumDoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumDoc.setPreferredSize(new java.awt.Dimension(150, 28));
        txtNumDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocKeyTyped(evt);
            }
        });
        rSPanel2.add(txtNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, -1));

        btnLimpiar.setBackground(new java.awt.Color(0, 153, 153));
        btnLimpiar.setBackgroundHover(new java.awt.Color(153, 204, 255));
        btnLimpiar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BACKSPACE);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        rSPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 30, 28));

        cboTipoDoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboTipoDoc.setPreferredSize(new java.awt.Dimension(93, 28));
        cboTipoDoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoDocItemStateChanged(evt);
            }
        });
        rSPanel2.add(cboTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 100, -1));

        txtClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtClave.setPreferredSize(new java.awt.Dimension(150, 28));
        rSPanel2.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 130, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Clave");
        rSPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        rSPanel1.add(rSPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 570));

        add(rSPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ClsECliente objEC=new ClsECliente();
        ClsNCliente objNC=new ClsNCliente();

        objEC.setNro_documento(txtNumDoc.getText());
        objEC.setNombre(txtNombres.getText());
        objEC.setApellido(txtApellidos.getText());   
        
        String dia = Integer.toString(txtCalendar.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(txtCalendar.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(txtCalendar.getCalendar().get(Calendar.YEAR));
        String fecha = (year + "-" + mes+ "-" + dia);
        
        objEC.setFech_nacimiento(fecha);
        objEC.setSexo(String.valueOf(cboSexo.getSelectedItem()));
        objEC.setDireccion(txtDireccion.getText());
        objEC.setCorreo(txtCorreo.getText());
        objEC.setCelular(txtCelular.getText());
        objEC.setClave(txtClave.getText());
        
        String idTipo=String.valueOf(cboTipoDoc.getSelectedItem());
        ClsNTipo_documento objND=new ClsNTipo_documento();
        for(ClsETipo_documento objE:objND.MtdListarTipo_documento()){
            if(idTipo.equals(objE.getDescripcion()))
            {
                objEC.setIdTip_documento(objE.getIdTipo_documento());
                break;
            }
        }
        
        if(objNC.MtdRegistrarCliente(objEC)==true){
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
            //GUARDAR HISTORIAL - REGISTRAR
            ClsNHistorial objetonegocioshistorial=new ClsNHistorial();
            ClsEHistorial objetoentidadhistorial = new ClsEHistorial();
            Date date = new Date();
            DateFormat FechaHora = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            objetoentidadhistorial.setFecha(FechaHora.format(date)+"");
            objetoentidadhistorial.setTipo("Insertar Cliente");
            objetoentidadhistorial.setAccion(lblNombres.getText()+" "+lblApellidos.getText()+ " registro un Cliente: "+txtNombres.getText()+" "+txtApellidos.getText());
            objetoentidadhistorial.setNro_doc(lblDni.getText());
            if(objetonegocioshistorial.MtdRegistrarHistorial(objetoentidadhistorial)==true){
            }
            else{
                JOptionPane.showMessageDialog(null, "Error al registrar accion.");
            }
            //FIN GUARDAR HISTORIAL - REGISTRAR
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Error de Datos");
        }
        ListarCliente();
        LimpiarCliente();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        ClsECliente objEC=new ClsECliente();
        ClsNCliente objNC=new ClsNCliente();
        
        //GUARDAR HISTORIAL - MODIFICAR
        ClsNHistorial objNH=new ClsNHistorial();
        ClsEHistorial objEH = new ClsEHistorial();
        Date date = new Date();
        DateFormat FechaHora = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String accion="";
        
        //Recorremos los resultados del método Listar.
        for(ClsECliente objE:objNC.MtdListarCliente()){
            //If para buscar el ID de la fila a modificar.
            if(txtNumDoc.getText().equals(String.valueOf(objE.getNro_documento()))){
                //If para buscar diferencias en los atributos.
                
                if(txtDireccion.getText().equals(objE.getDireccion())){
                    
                }
                else{
                    //Insersión en la tabla Historial.
                    objEH.setFecha(FechaHora.format(date)+"");
                    objEH.setTipo("Modificar Cliente");
                    objEH.setAccion(lblNombres.getText()+" "+lblApellidos.getText()+ " modifico el Cliente:"+objE.getNro_documento()+" - Direccion: "+objE.getDireccion()+" a "+txtDireccion.getText());
                    objEH.setNro_doc(lblDni.getText());
                    if(objNH.MtdRegistrarHistorial(objEH)==true){
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Error al registrar accion.");
                    }
                }
                //=============
                if(txtCorreo.getText().equals(objE.getCorreo())){
                    
                }
                else{
                    //Insersión en la tabla Historial.
                    objEH.setFecha(FechaHora.format(date)+"");
                    objEH.setTipo("Modificar Cliente");
                    objEH.setAccion(lblNombres.getText()+" "+lblApellidos.getText()+ " modifico el Cliente:"+objE.getNro_documento()+" - Correo: "+objE.getCorreo()+" a "+txtCorreo.getText());
                    objEH.setNro_doc(lblDni.getText());
                    if(objNH.MtdRegistrarHistorial(objEH)==true){
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Error al registrar accion.");
                    }
                }
                //=============
                if(txtCelular.getText().equals(objE.getCelular())){
                    
                }
                else{
                    //Insersión en la tabla Historial.
                    objEH.setFecha(FechaHora.format(date)+"");
                    objEH.setTipo("Modificar Cliente");
                    objEH.setAccion(lblNombres.getText()+" "+lblApellidos.getText()+ " modifico el Cliente:"+objE.getNro_documento()+" - Celular: "+objE.getCelular()+" a "+txtCelular.getText());
                    objEH.setNro_doc(lblDni.getText());
                    if(objNH.MtdRegistrarHistorial(objEH)==true){
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Error al registrar accion.");
                    }
                }
                //=============
                if(cboSexo.getSelectedItem().equals(objE.getSexo())){
                    
                }
                else{
                    //Insersión en la tabla Historial.
                    objEH.setFecha(FechaHora.format(date)+"");
                    objEH.setTipo("Modificar Cliente");
                    objEH.setAccion(lblNombres.getText()+" "+lblApellidos.getText()+ " modifico el Cliente:"+objE.getNro_documento()+" - Sexo: "+objE.getSexo()+" a "+cboSexo.getSelectedItem());
                    objEH.setNro_doc(lblDni.getText());
                    if(objNH.MtdRegistrarHistorial(objEH)==true){
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Error al registrar accion.");
                    }
                }
                //=============
                String dia1 = Integer.toString(txtCalendar.getCalendar().get(Calendar.DAY_OF_MONTH));
                String mes1 = Integer.toString(txtCalendar.getCalendar().get(Calendar.MONTH) + 1);
                String year1 = Integer.toString(txtCalendar.getCalendar().get(Calendar.YEAR));
                String fecha1 = (year1 + "-" + mes1+ "-" + dia1);
                if(fecha1.equals(objE.getFech_nacimiento())){
                    
                }
                else{
                    dia1 = Integer.toString(txtCalendar.getCalendar().get(Calendar.DAY_OF_MONTH));
                    mes1 = Integer.toString(txtCalendar.getCalendar().get(Calendar.MONTH) + 1);
                    year1 = Integer.toString(txtCalendar.getCalendar().get(Calendar.YEAR));
                    fecha1 = (year1 + "-" + mes1+ "-" + dia1);
                    //Insersión en la tabla Historial.
                    objEH.setFecha(FechaHora.format(date)+"");
                    objEH.setTipo("Modificar Cliente");
                    objEH.setAccion(lblNombres.getText()+" "+lblApellidos.getText()+ " modifico el Cliente:"+objE.getNro_documento()+" - Fech Nacimiento: "+objE.getFech_nacimiento()+" a "+fecha1);
                    objEH.setNro_doc(lblDni.getText());
                    if(objNH.MtdRegistrarHistorial(objEH)==true){
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Error al registrar accion.");
                    }
                }
            }
            
            
        }
        
        //FIN GUARDAR HISTORIAL - MODIFICAR
        
        
        objEC.setNro_documento(txtNumDoc.getText());
        objEC.setNombre(txtNombres.getText());
        objEC.setApellido(txtApellidos.getText());   
        
        String dia = Integer.toString(txtCalendar.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(txtCalendar.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(txtCalendar.getCalendar().get(Calendar.YEAR));
        String fecha = (year + "-" + mes+ "-" + dia);
        
        objEC.setFech_nacimiento(fecha);
        objEC.setSexo(String.valueOf(cboSexo.getSelectedItem()));
        objEC.setDireccion(txtDireccion.getText());
        objEC.setCorreo(txtCorreo.getText());
        objEC.setCelular(txtCelular.getText());
        objEC.setClave(txtClave.getText());
        
        String idTipo=String.valueOf(cboTipoDoc.getSelectedItem());
        ClsNTipo_documento objND=new ClsNTipo_documento();
        for(ClsETipo_documento objE:objND.MtdListarTipo_documento()){
            if(idTipo.equals(objE.getDescripcion()))
            {
                objEC.setIdTip_documento(objE.getIdTipo_documento());
                break;
            }
        }
        
        if(objNC.MtdModificarCliente(objEC)==true){
            JOptionPane.showMessageDialog(null, "Datos modificados correctamente.");
        }
        else{
            JOptionPane.showMessageDialog(null, "Error de Datos");
        }
        ListarCliente();
        LimpiarCliente();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDNIActionPerformed
        // TODO add your handling code here:
        String tiposelect=String.valueOf(cboTipoDoc.getSelectedItem());
        if(tiposelect.equals("DNI")){
            String token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFuY29icmlhbjZAZ21haWwuY29tIn0.PTLq2kMGMK3A5XTbdmRAUMDLRn3f5eS2eMF1TV0CtLM";
            String dni=txtNumDoc.getText();
            String enlace="https://dniruc.apisperu.com/api/v1/dni/" + dni + "?token=" + token;
            try {
                URL url=new URL(enlace);
                URLConnection request=url.openConnection();
                request.connect();

                JsonParser jp= new JsonParser();
                JsonElement root = jp.parse(new InputStreamReader((InputStream)request.getContent()));
                if(root.isJsonObject()){
                    JsonObject rootobj = root.getAsJsonObject();

                    String apellidos;
                    String ape1=rootobj.get("apellidoPaterno").getAsString();
                    String ape2=rootobj.get("apellidoMaterno").getAsString();
                    String nombres=rootobj.get("nombres").getAsString();
                    apellidos=ape1+" "+ape2;
                    txtNombres.setText(nombres);
                    txtApellidos.setText(apellidos);
                    
                    txtNumDoc.setEditable(false);
                    txtNombres.setEditable(false);
                    txtApellidos.setEditable(false);
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Solo se puede buscar DNI");
        }
                
    }//GEN-LAST:event_btnBuscarDNIActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        // TODO add your handling code here:
        txtNumDoc.setEditable(false);

        int seleccionar=tblClientes.rowAtPoint(evt.getPoint());
        
        txtNumDoc.setText(String.valueOf(tblClientes.getValueAt(seleccionar, 0)));
        txtNombres.setText(String.valueOf(tblClientes.getValueAt(seleccionar, 1)));
        
        ClsNCliente objNC=new ClsNCliente();
        for(ClsECliente objE:objNC.MtdListarCliente()){
            
            if(txtNumDoc.getText().equals(objE.getNro_documento()))
            {
                txtApellidos.setText(objE.getApellido());
                
                SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
                String strFecha = objE.getFech_nacimiento();
                Date fecha = null;
                try {
                    fecha = formatoDelTexto.parse(strFecha);
                } catch (ParseException ex) {
                    ex.printStackTrace();
                }
                txtCalendar.setDate(fecha);
                    //txtFechaNac.setText(String.valueOf(objE.getFech_nacimiento()));
                String sexo=objE.getSexo();
                    //JOptionPane.showMessageDialog(null, sexo);
                if(sexo.equals("Masculino"))
                    {
                        cboSexo.setSelectedItem("Masculino");
                    }
                    if(sexo.equals("Femenino"))
                    {
                        cboSexo.setSelectedItem("Femenino");               
                    }
                txtDireccion.setText(objE.getDireccion());
                txtCorreo.setText(objE.getCorreo());
                txtCelular.setText(objE.getCelular());
                txtClave.setText(objE.getClave());
                
                int idTipo_doc=objE.getIdTip_documento();
                ClsNTipo_documento objNR=new ClsNTipo_documento();
                for(ClsETipo_documento objER:objNR.MtdListarTipo_documento()){
                    if(idTipo_doc==objER.getIdTipo_documento())
                    {
                        String tipodoc=String.valueOf(objER.getDescripcion());
                        cboTipoDoc.setSelectedItem(tipodoc);
                        break;
                    }
                }
                String tiposelect=String.valueOf(cboTipoDoc.getSelectedItem());
                if(tiposelect.equals("DNI")){
                    txtNombres.setEditable(false);
                    txtApellidos.setEditable(false);
                    txtNumDoc.setEditable(false);
                }
                else{
                    txtNombres.setEditable(true);
                    txtApellidos.setEditable(true);
                    txtNumDoc.setEditable(true);
                }
                
                break;
            }
        }
        ListarCliente();
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        LimpiarCliente();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNumDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyTyped
        // TODO add your handling code here:
        if(cboTipoDoc.getSelectedItem().equals("DNI")){
            if (txtNumDoc.getText().length()== 8) 
            evt.consume();             
        }   
    }//GEN-LAST:event_txtNumDocKeyTyped

    private void cboTipoDocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoDocItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoDocItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btnBuscarDNI;
    private RSMaterialComponent.RSButtonMaterialIconOne btnEditar;
    private RSMaterialComponent.RSButtonMaterialIconOne btnGuardar;
    private RSMaterialComponent.RSButtonMaterialIconOne btnLimpiar;
    private javax.swing.JComboBox<String> cboSexo;
    private static javax.swing.JComboBox<String> cboTipoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblFecha2;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblSexo;
    private necesario.RSPanel rSPanel1;
    private necesario.RSPanel rSPanel2;
    private static javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellidos;
    private com.toedter.calendar.JDateChooser txtCalendar;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumDoc;
    // End of variables declaration//GEN-END:variables

   
}
