/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Entidad.*;
import Negocios.*;
import static Presentacion.FrmPrincipal.lblApellidos;
import static Presentacion.FrmPrincipal.lblDni;
import static Presentacion.FrmPrincipal.lblNombres;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Brian Anco
 */
public class PnlHistorial extends javax.swing.JPanel {

    /**
     * Creates new form PnlOrdenes
     */
    public PnlHistorial() {
        initComponents();
        ListarEmpleados();
    }

    public static void ListarEmpleados(){
        lblTitulo.setText("HISTORIAL - EMPLEADOS");
        DefaultTableModel modelo = (DefaultTableModel) tblHistorial.getModel();
        try {
            int filas=tblHistorial.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
        ClsNHistorial objNC=new ClsNHistorial();
        String[] datos=new String[5];
        for(ClsEHistorial objE:objNC.MtdListarHistorial()){
            datos[0]=objE.getFecha();
            datos[1]=objE.getTipo();
            datos[2]=objE.getAccion();
            datos[3]=objE.getNro_doc();
            modelo.addRow(datos);
        }
        TableRowSorter<TableModel> Id = new TableRowSorter<>(modelo);
        tblHistorial.setRowSorter(Id);
        tblHistorial.getRowSorter().toggleSortOrder(0);
    }
    
    public static void ListarClientes(){
        lblTitulo.setText("HISTORIAL - CLIENTES");
        DefaultTableModel modelo = (DefaultTableModel) tblHistorial.getModel();
        try {
            int filas=tblHistorial.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
        ClsNHistorial objNC=new ClsNHistorial();
        String[] datos=new String[5];
        for(ClsEHistorial objE:objNC.MtdListarHistorialCliente()){
            datos[0]=objE.getFecha();
            datos[1]=objE.getTipo();
            datos[2]=objE.getAccion();
            datos[3]=objE.getNro_doc();
            modelo.addRow(datos);
        }
        TableRowSorter<TableModel> Id = new TableRowSorter<>(modelo);
        tblHistorial.setRowSorter(Id);
        tblHistorial.getRowSorter().toggleSortOrder(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanel1 = new necesario.RSPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        btnEmpleados = new RSMaterialComponent.RSButtonMaterialOne();
        btnClientes = new RSMaterialComponent.RSButtonMaterialOne();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanel1.setColorBackground(new java.awt.Color(255, 255, 255));
        rSPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(235, 73, 51));
        lblTitulo.setText("HISTORIAL - EMPLEADOS");
        rSPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        tblHistorial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Tipo", "Accion", "Nro. Doc."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblHistorial);
        if (tblHistorial.getColumnModel().getColumnCount() > 0) {
            tblHistorial.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblHistorial.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblHistorial.getColumnModel().getColumn(3).setPreferredWidth(5);
        }

        rSPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 950, 470));

        btnEmpleados.setBackground(new java.awt.Color(0, 102, 204));
        btnEmpleados.setText("Historial de Empleados");
        btnEmpleados.setBackgroundHover(new java.awt.Color(51, 102, 255));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        rSPanel1.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 180, 28));

        btnClientes.setBackground(new java.awt.Color(178, 0, 168));
        btnClientes.setText("Historial de Clientes");
        btnClientes.setBackgroundHover(new java.awt.Color(178, 0, 255));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        rSPanel1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 180, 28));

        add(rSPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        ListarEmpleados();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        ListarClientes();
    }//GEN-LAST:event_btnClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialOne btnBoleta;
    private RSMaterialComponent.RSButtonMaterialOne btnBoleta1;
    private RSMaterialComponent.RSButtonMaterialOne btnBoleta2;
    private RSMaterialComponent.RSButtonMaterialOne btnBoleta3;
    private RSMaterialComponent.RSButtonMaterialOne btnBoleta4;
    private RSMaterialComponent.RSButtonMaterialOne btnBoleta5;
    private RSMaterialComponent.RSButtonMaterialOne btnBoleta6;
    private RSMaterialComponent.RSButtonMaterialOne btnBoleta7;
    private RSMaterialComponent.RSButtonMaterialOne btnClientes;
    private RSMaterialComponent.RSButtonMaterialOne btnEmpleados;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JLabel lblTitulo;
    private necesario.RSPanel rSPanel1;
    private static javax.swing.JTable tblHistorial;
    // End of variables declaration//GEN-END:variables
}
