/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import Negocios.ClsConexion;

/**
 *
 * @author Brian Anco
 */
public class PnlInicio extends javax.swing.JPanel{

    /**
     * Creates new form PnlInicio
     */
    public PnlInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelImage1 = new rojeru_san.rspanel.RSPanelImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1150, 570));
        setPreferredSize(new java.awt.Dimension(1010, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/LogoOmylab.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 200, 55));
    }// </editor-fold>//GEN-END:initComponents

    public static void MostrarReporte() throws JRException, net.sf.jasperreports.engine.JRException{
        Map parameters = new HashMap();
        //parameters.put("codigo", "descripcion");
        //parameters.put("FECHA", new java.util.Date());
        String Nombre="report1";
        String path = "D:\\Universidad\\Laboratorios Programación III\\Omylab\\src\\Presentacion\\Reportes\\"+Nombre+".jrxml";
        JasperReport report = JasperCompileManager.compileReport(path);
        JasperPrint print = JasperFillManager.fillReport(report, parameters,ClsConexion.Conectar());
         // Exporta el informe a PDF
        JasperExportManager.exportReportToPdfFile(print,"D:\\Universidad\\Laboratorios Programación III\\Omylab\\src\\Presentacion\\ReportesPdf\\"+Nombre+".pdf");
        //Para visualizar el pdf directamente desde java
        JasperViewer.viewReport(print, false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rspanel.RSPanelImage rSPanelImage1;
    // End of variables declaration//GEN-END:variables
}
